import { pathToFileURL } from 'url';
const repo = 'C:/Users/bear9/OpenCharts';
const I = await import(pathToFileURL(repo + '/src/pine/interpreter.ts'));
console.log('exports:', Object.keys(I).filter(k => k.startsWith('__')));
const P = await import(pathToFileURL(repo + '/src/pine/parser.ts'));
const B = await import(pathToFileURL(repo + '/src/pine/builtins/index.ts'));
const parsed = P.parse('indicator("t")\nplot(close)');
console.log('body.len:', parsed.body?.length, 'decl:', parsed.decl?.type);
const bars = [{openTime:0,open:1,high:1,low:1,close:1,volume:1},{openTime:1,open:1,high:1,low:1,close:1,volume:1}];
const before = I.__compileCalls;
const r = await I.runScript(parsed, bars, {});
console.log('compileCalls+', I.__compileCalls - before, 'plots', r.plots.size);
